from progress_decorator.wrappers.callpoint import CallPoint
from progress_decorator.wrappers.endpoint import EndPoint
from progress_decorator.wrappers.function import FunctionEndPoint
from progress_decorator.wrappers.iterable import IterableEndPoint
