name: Lint and Test 🧪

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - dev
      - master

jobs:
  lint-black:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: psf/black@stable
  lint-isort:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: isort/isort-action@v1
  test:
    name: Run tests 🧪
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run pytest
      run: |
        pip install pytest pytest-cov
        pytest --cov=src --cov-report=xml --cov-report=html
